site_name: PHP Debug Bar
site_author: Barry vd. Heuvel
site_description: PHP Debug Bar
site_url: https://php-debugbar.com
repo_url: https://github.com/php-debugbar/php-debugbar
copyright: Copyright &copy; Barry vd. Heuvel & Maxime Bouroumeau-Fuseau

nav:
  - DebugBar: index.md
  - Documentation:
      - Getting started: docs/index.md
      - docs/data-collectors.md
      - docs/rendering.md
      - docs/ajax-and-stack.md
      - docs/data-formatter.md
      - docs/storage.md
      - docs/openhandler.md
      - docs/http-drivers.md
      - docs/javascript-bar.md
  - Collectors:
      - collectors/base.md
      - collectors/bridge.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_white.png
  favicon: assets/favicon.png
  palette:
    - primary: custom
      accent: custom
      scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.instant
    - navigation.tracking
#    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - content.tooltips
    - content.code.copy
    - toc.follow
    - toc.integrate
    - search.highlight
    - meta
extra_css:
  - assets/dist/debugbar.min.css
  - assets/extra.css
extra_javascript:
  - assets/dist/debugbar.min.js
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: php-debugbar
      repo: php-debugbar

extra:
  analytics:
    provider: google
    property: G-RRZHNXY76R
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/php-debugbar/php-debugbar

hooks:
  - docs/overrides/shortcodes.py
