name: Check Minified Files

on:
  push:
    branches:
      - master
    paths:
      - 'resources/**'
  pull_request:
    branches:
      - "*"
    paths:
      - 'resources/**'

permissions:
  contents: write

jobs:
  build-assets:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    name: Build Minified Files

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: Build all files
      run: npm run lint:fix

    - name: Build all files
      run: npm run build

    - name: Commit Compiled Files
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update Assets